// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThietBiDienTu.Data;

#nullable disable

namespace ThietBiDienTu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127103944_Create_table_HangHoa")]
    partial class Create_table_HangHoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ThietBiDienTu.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHH")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThongTinHH")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHH");

                    b.ToTable("HangHoa");
                });
#pragma warning restore 612, 618
        }
    }
}
